### ISSUE TITLE
Actor testing utils for git

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/cli#53]
Since the actors usually result in creating branches and committing code, it might be nice if there were a few more test configs to help test the results of that? In the past I've done a lot of this by hand, but it can be pretty tedious.

What if you could do...
```yml
- name: Basic lockfile test
  dockerfile: Dockerfile
  repo_contents: tests/actor/basic/repo_base
  input_dependencies_json: tests/actor/basic/input.json
  output_dependencies_json: tests/actor/basic/output.json
  git_results:
    branches:
      lockfile-update-1:
        commits:
        - message: Update yarn.lock
```

Maybe doesn't have to be quite that verbose, but it could also check commit author, maybe compare a `git diff` to a string, etc.
